services:
  - type: web
    name: indibuz-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn indibuz_core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: indibuz-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://yourdomain.com,https://www.yourdomain.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://yourdomain.com,https://www.yourdomain.com

databases:
  - name: indibuz-db
    databaseName: indibuz
    user: indibuz_user
    plan: free
